name: Face Recognition Attendance System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-tk \
            python3-opencv \
            libgl1-mesa-glx \
            libglib2.0-0 \
            xvfb

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            tensorflow \
            pillow \
            pandas \
            scipy \
            numpy \
            opencv-python

      - name: Run with virtual display
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
          python apptest1.py

